In [55]:
import numpy as np
import pandas as pd

In [2]:
arrl1 = np.array([3,-3,2,-2])

In [3]:
type(arrl1)

numpy.ndarray

In [4]:
arrl1

array([ 3, -3,  2, -2])

In [17]:
arrl1 = np.array([3,-3,2,-2],dtype='int')

In [13]:
arrl1

array(['3', '-3', '2', '-2'], dtype='<U2')

In [14]:
arrl2 = np.array([3,-3,2,-2,"1"])

In [15]:
arrl2.dtype

dtype('<U21')

In [16]:
arrl1.dtype

dtype('<U2')

In [20]:
s = np.array([1,23,4,25,6,4,7,2,36,235,247,23,52,1,2,5])
np.sort(s)

array([  1,   1,   2,   2,   4,   4,   5,   6,   7,  23,  23,  25,  36,
        52, 235, 247])

In [21]:
s

array([  1,  23,   4,  25,   6,   4,   7,   2,  36, 235, 247,  23,  52,
         1,   2,   5])

In [22]:
s = np.sort(s)

In [23]:
s

array([  1,   1,   2,   2,   4,   4,   5,   6,   7,  23,  23,  25,  36,
        52, 235, 247])

In [28]:
sorted(s,reverse = True)

[247, 235, 52, 36, 25, 23, 23, 7, 6, 5, 4, 4, 2, 2, 1, 1]

In [29]:
np.array(sorted(s,reverse = True))

array([247, 235,  52,  36,  25,  23,  23,   7,   6,   5,   4,   4,   2,
         2,   1,   1])

In [30]:
np.argsort(s)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [31]:
np.argsort(sorted(s,reverse = True))

array([14, 15, 12, 13, 10, 11,  9,  8,  7,  5,  6,  4,  3,  2,  1,  0])

In [34]:
arr10=np.array([[1,2,4,5],[21,52,-21,2],[1.24,22,42,-12]])

In [36]:
np.sort(arr10,axis=1)

array([[  1.  ,   2.  ,   4.  ,   5.  ],
       [-21.  ,   2.  ,  21.  ,  52.  ],
       [-12.  ,   1.24,  22.  ,  42.  ]])

In [37]:
arr10

array([[  1.  ,   2.  ,   4.  ,   5.  ],
       [ 21.  ,  52.  , -21.  ,   2.  ],
       [  1.24,  22.  ,  42.  , -12.  ]])

In [38]:
np.sort(arr10,axis=0)

array([[  1.  ,   2.  , -21.  , -12.  ],
       [  1.24,  22.  ,   4.  ,   2.  ],
       [ 21.  ,  52.  ,  42.  ,   5.  ]])

In [41]:
np.where(s>5,10,s)

array([ 1,  1,  2,  2,  4,  4,  5, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [42]:
s

array([  1,   1,   2,   2,   4,   4,   5,   6,   7,  23,  23,  25,  36,
        52, 235, 247])

In [47]:
np.extract(s>11,s) #只能写s

array([ 23,  23,  25,  36,  52, 235, 247])

In [57]:
pd.Series([1,2],index=2,name="This")

TypeError: Index(...) must be called with a collection of some kind, 2 was passed

In [63]:
series = pd.Series([2.8,3.01,8.99,5.18],index=['a','b','c','d'],name="This is a series, lalala")

In [59]:
type(series)

pandas.core.series.Series

In [64]:
series

a    2.80
b    3.01
c    8.99
d    5.18
Name: This is a series, lalala, dtype: float64

In [66]:
series3= pd.Series({'Beijing':2.8,'Shanghai':3.1,'Guangdong':4.1,'Shenzhen':3.5})

In [67]:
series3 #Dictionary里，嘻嘻嘻index是前面的啊

Beijing      2.8
Shanghai     3.1
Guangdong    4.1
Shenzhen     3.5
dtype: float64

In [68]:
series3['Beijing']

2.8

In [70]:
series3['Beijing':'Guangdong']

Beijing      2.8
Shanghai     3.1
Guangdong    4.1
dtype: float64

In [71]:
series3[0:3]

Beijing      2.8
Shanghai     3.1
Guangdong    4.1
dtype: float64

In [73]:
series3.values#输出的是ndarray

array([2.8, 3.1, 4.1, 3.5])

In [74]:
series3.index

Index(['Beijing', 'Shanghai', 'Guangdong', 'Shenzhen'], dtype='object')

In [75]:
series.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [77]:
series.dtypes

dtype('float64')

In [81]:
#DataFrame is 表结构 【超级常用】
list1 = [['张三',23,'男'],['李四',27,'女'],['王五',18,'女']]
df1 = pd.DataFrame(list1,columns = ['姓名','年龄','性别'])


In [83]:
df1.head(100)

姓名  年龄 姓名
0  张三  23  男
1  李四  27  女
2  王五  18  女

In [84]:
df1.head(1)

姓名  年龄 姓名
0  张三  23  男

In [85]:
df2 = pd.DataFrame({'姓名':['张三','李四','王二'],'Age':[23,27,18],'Gender':['Male','Female','Female']})

In [88]:
df2.head(3)

姓名  Age  Gender
0  张三   23    Male
1  李四   27  Female
2  王二   18  Female

In [90]:
array1=np.array(list1)

In [92]:
df3 = pd.DataFrame(array1, columns=['Name','Age','Gender'],index = ['a','b','c'])

In [93]:
df3

Name Age Gender
a   张三  23      男
b   李四  27      女
c   王五  18      女

In [96]:
df3.values


array([['张三', '23', '男'],
       ['李四', '27', '女'],
       ['王五', '18', '女']], dtype=object)

In [97]:
df3.index

Index(['a', 'b', 'c'], dtype='object')

In [98]:
df3.columns

Index(['Name', 'Age', 'Gender'], dtype='object')

In [99]:
df3.columns.tolist()

['Name', 'Age', 'Gender']

In [100]:
df3.ndim

2

In [101]:
df3.shape

(3, 3)

In [106]:
series.shape

(4,)

In [107]:
df3.size #元素个数

9

In [111]:
df3.dtypes #Array把他们object化了

Name      object
Age       object
Gender    object
dtype: object

In [112]:
df2.dtypes

姓名        object
Age        int64
Gender    object
dtype: object

In [113]:
df1.dtypes

姓名    object
年龄     int64
姓名    object
dtype: object